---
# General information about the Necesse Server:
#
# All server data is stored in `/.config/Necesse/`
#
# The main configuration file is `/.config/Necesse/cfg/server.cfg`, which contains sensitive information
# like the server password.
# The path can be changed by passing the `-settings` argument to the server executable.
#
# Another configuration file is `/.config/Necesse/cfg/settings.cfg`, which contains game settings.
# I don't know which of these settings are used for the server. I only know that `zipSaves` needs to be set to false,
# since the zip save always seems to be broken.
#
# The world configuration is located at `/.config/Necesse/saves/worlds/<world-name>/worldSettings.cfg`.
# Usually it's generated automatically when the world is created, but this kind of defeats the purpose.
# Note that it's stored in a directory equal to the world name, which is set using the `-world` argument.

# -- The api versions of the resources created by this chart.
#
# Ref: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
apiVersions:
  deployment: "apps/v1"
  persistentVolumeClaim: "v1"
  service: "v1"
  podDisruptionBudget: "policy/v1"
  serviceAccount: "v1"
  configMap: "v1"
  statefulSet: "apps/v1"

# -- Use this to override the name of the chart.
nameOverride: ""

# -- Use this to override the fullname of the chart.
fullnameOverride: ""

# -- Use this to override the namespace of the chart.
# By default, `.Release.Namespace` is used.
namespaceOverride: ""

# -- The number of replicas of the pod.
# Necesse doesn't support running multiple replicas. Increase this value at your own risk.
#
# Ref: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# -- The image of the container.
#
# Ref: https://kubernetes.io/docs/concepts/containers/images/
image:
  # -- The repository/name/url of the image.
  repository: "ghcr.io/ernail/necesse-server"
  # -- The pull policy for the image.
  pullPolicy: "Always"
  # -- The tag of the image. If not set, the chart's `appVersion` is used.
  tag: ""

# -- Secrets for pulling an image from a private repository.
#
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# -- Annotations to add to the pod(s).
#
# Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- Extra labels to add to the pod(s).
#
# Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
extraPodLabels: {}

# -- Resource limits and requests.
# You might want to set `limits.cpu` to `null`: https://home.robusta.dev/blog/stop-using-cpu-limits
#
# Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources:
  requests:
    cpu: "100m"
    memory: "1024Mi"
    ephemeral-storage: "128Mi"
  limits:
    cpu: "100m"
    memory: "1024Mi"
    ephemeral-storage: "128Mi"

# -- The security context for the pod.
#
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext:
  fsGroup: 10001

# -- The security context for the container.
#
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
containerSecurityContext:
  readOnlyRootFilesystem: true
  runAsUser: 10001
  runAsGroup: 10001

# -- The node selector for the pod(s).
#
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}

# -- The affinity for the pod(s).
#
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
affinity: {}

# -- A host podAntiAffinity, that stops multiple pods from from being scheduled on the same node.
#
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
hostPodAntiAffinity:
  # -- Whether to enable the host podAntiAffinity.
  enabled: false
  # -- The weight of the host podAntiAffinity.
  weight: 50

# -- The tolerations for the pod(s).
#
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: {}

# -- Liveness Probe configuration.
# Liveness probes can be dangerous. Only use them if you really need one.
# See https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html for more information.
#
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe: {}
  # httpGet:
  #   # -- The path to use for the liveness probe.
  #   path: "/live"
  #   # -- The port to use for the liveness probe.
  #   # This should reference the container ports defined at `.Values.containerPorts`.
  #   port: "http"

# -- Readiness Probe configuration.
#
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
readinessProbe:
  exec:
    command:
      - "pgrep"
      - "-f"
      - "Server.jar"

# -- Deployment strategy configuration.
#
# Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
strategy:
  type: "RollingUpdate"

# -- ConfigMap configuration.
#
# Ref: https://kubernetes.io/docs/concepts/configuration/configmap/
configMap:
  # -- Whether to create a ConfigMap resource.
  enabled: false
  # -- The name of the ConfigMap.
  # The name should reference the ConfigMap name at `.Values.volumeConfig`.
  name: "config"
  # -- Annotations to add to the ConfigMap.
  annotations: {}
  # -- The data to add to the ConfigMap.
  # The `server.cfg` needs to be created as a secret, since it can contain sensitive information like passwords.
  # Check the `examples` directory for an example of an encrypted `server.cfg` Secret.
  data: {}

# -- Volumes configuration
#
# Ref: https://kubernetes.io/docs/concepts/storage/volumes/
volumes:
  - name: "data"
    # -- By default, the data volume is not persisted.
    # To enable persistence, you need to remove `emptyDir`, uncomment the `persistentVolumeClaim` section,
    # and set `.Values.persistentVolumeClaims.data.enabled` to `true`.
    emptyDir: {}
    # persistentVolumeClaim:
    #  # -- The name of the persistent volume claim to use.
    #  # This should reference a PVC at `.Values.persistentVolumeClaims`.
    #  claimName: "data"
  - name: "server-config"
    secret:
      # The name of the secret containing the `server.cfg` file.
      secretName: "necesse-server-config"

# -- Volume mounts configuration
# The map will be transformed to an array
#
# Ref: https://kubernetes.io/docs/concepts/storage/volumes/#mounting-a-volume-in-a-container
volumeMounts:
  - name: "data"
    mountPath: "/.config/Necesse"
  - name: "data"
    mountPath: "/.config/Necesse/cfg"
    subPath: "cfg"
  - name: "server-config"
    mountPath: "/.config/Necesse/cfg/server.cfg"
    subPath: "server.cfg"

# -- Persistent Volume Claims configuration.
#
# Ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
persistentVolumeClaims:
  data:
    # -- Whether to enable the Persistent Volume Claim.
    # Settings this value to `true` will only create the PVC.
    # You still need to adapt `.Values.volumes` to use the claim.
    enabled: false
    # -- The name of the Persistent Volume Claim.
    pvcName: "data"
    # -- Annotations to add to the Persistent Volume Claim.
    annotations: {}
    # -- The access modes of the Persistent Volume Claim.
    accessModes:
      - "ReadWriteOnce"
    # -- The size of the Persistent Volume Claim.
    size: "1Gi"
    # -- The storage class of the Persistent Volume Claim.
    storageClass: ""

# -- Configuration for service accounts.
#
# Ref: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # -- Whether a service account should be created.
  enabled: true
  # -- Whether to mount a ServiceAccount's API credentials.
  automount: true
  # -- Annotations to add to the service account.
  annotations: {}
  # -- The name of the service account to use.
  # If not set, a name is generated based on the chart name.
  name: ""

# -- The ports of the container.
# To use these ports in the service(s),
# you need to add them to `.Values.service.ports` or `.Values.metrics.service.ports`.
#
# If `.Values.livenessProbe.enabled` is true, you need to add them to `.Values.livenessProbe`.
#
# If `.Values.readinessProbe.enabled` is true, you need to add them to `.Values.readinessProbe`.
#
# Ref: https://kubernetes.io/docs/concepts/services-networking/service/
#
# Ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
containerPorts:
  - name: "server"
    port: 14159
    protocol: "UDP"

# -- Service configuration.
# A service for metrics is created separately. Check `.Values.metrics` for more information.
#
# Ref: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # -- The type of service to create.
  #
  # Ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: "ClusterIP"
  # -- The ports of the service.
  # These should reference the container ports defined at `.Values.containerPorts`.
  # When `.Values.ingress.enabled` is `true`, they should reference `.Values.ingress.hosts`.
  #
  # Ref: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  ports:
    - name: "server"
      port: 14159
      protocol: "UDP"
      targetPort: "server"

# -- Pod Disruption Budget configuration.
#
# Ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
podDisruptionBudget:
  # -- Whether to create a PodDisruptionBudget resource.
  enabled: false
  # -- Annotations to add to the PodDisruptionBudget.
  annotations: {}
  # -- The minimum number of pods that must be available. If set, maxUnavailable won't be used.
  minAvailable: 1
  # -- The maximum number of pods that can be unavailable. Ignored if `minAvailable` is set.
  maxUnavailable: 1
  # -- The Unhealthy Pod Eviction Policy.
  unhealthyPodEvictionPolicy: "AlwaysAllow"

# -- App configuration.
app:
  # -- Environment variables to pass to the container.
  #
  # Ref: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
  env:
    # -- The JVM options.
    # Most of these are recommended by the official Necesse server documentation.
    # `-Xms` and `-Xmx` should be set according to `.Values.resources`.
    - name: "JAVA_TOOL_OPTIONS"
      value: >-
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseG1GC
        -XX:+ExplicitGCInvokesConcurrent
        -XX:G1NewSizePercent=20
        -XX:G1ReservePercent=20
        -XX:MaxGCPauseMillis=50
        -XX:G1HeapRegionSize=32M
        -Xms256M
        -Xmx256M
  # -- Arguments to pass to the containers entrypoint.
  #
  # Ref: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
  args:
    - "-world"
    - "kubeworld"
    - "-zipsaves"
    - "0"