{{- range $key, $pvc := .Values.persistentVolumeClaims }}
{{- if $pvc.enabled }}
---
kind: "PersistentVolumeClaim"
apiVersion: {{ $.Values.apiVersions.persistentVolumeClaim | quote }}
metadata:
  name: {{ $pvc.pvcName | quote }}
  namespace: {{ include "names.namespace" $ | quote }}
  labels:
    {{- include "labels.commonLabels" $ | nindent 4 }}
  {{- with $pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml $pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $pvc.size | quote }}
  storageClassName: {{ $pvc.storageClass | quote }}
...
{{- end }}
{{- end }}
