{{- range $key, $config := .Values.volumeConfig }}
{{- if and $config.persistence $config.persistence.enabled }}
---
kind: "PersistentVolumeClaim"
apiVersion: {{ $.Values.apiVersions.persistentVolumeClaim | quote }}
metadata:
  name: {{ $config.persistence.pvcName | quote }}
  namespace: {{ include "names.namespace" $ | quote }}
  labels:
    {{- include "labels.commonLabels" $ | nindent 4 }}
  {{- with $config.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{ toYaml $config.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $config.persistence.size | quote }}
  storageClassName: {{ $config.persistence.storageClass | quote }}
...
{{- end }}
{{- end }}
