---
resources:
  requests:
    cpu: "100m"
    memory: "1024Mi"
    ephemeral-storage: "128Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"
    ephemeral-storage: "128Mi"

volumes:
  - name: "data"
    persistentVolumeClaim:
      claimName: "data"
  - name: "server-config"
    secret:
      # The name of the secret containing the `server.cfg` file.
      secretName: "necesse-server-config"

persistentVolumeClaims:
  data:
    enabled: true
    size: "1Gi"
    storageClass: "longhorn"

service:
  type: "LoadBalancer"
